# CodeRabbit Configuration
# Simplified to match the latest schema requirements

language: "en-US"
reviews:
  profile: "assertive"
  collapse_walkthrough: false
  auto_review:
    enabled: true
    ignore_title_keywords: ["WIP", "draft"]
  tools:
    shellcheck:
      enabled: true
